// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/board.tsx";
import * as $$2 from "./islands/conduct.tsx";
import * as $$3 from "./islands/hello.tsx";
import * as $$4 from "./islands/message.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/board.tsx": $$1,
    "./islands/conduct.tsx": $$2,
    "./islands/hello.tsx": $$3,
    "./islands/message.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
