// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/joke.ts";
import * as $1 from "./routes/index.tsx";
import * as $$0 from "./islands/board.tsx";
import * as $$1 from "./islands/conduct.tsx";
import * as $$2 from "./islands/hello.tsx";
import * as $$3 from "./islands/message.tsx";

const manifest = {
  routes: {
    "./routes/api/joke.ts": $0,
    "./routes/index.tsx": $1,
  },
  islands: {
    "./islands/board.tsx": $$0,
    "./islands/conduct.tsx": $$1,
    "./islands/hello.tsx": $$2,
    "./islands/message.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
